[build]
command = "npm run prebuild && npx nx build Angular-Movie-App --configuration=production --no-cloud"
environment = { NODE_VERSION = "18" }
publish = "dist/Angular-Movie-App/browser"
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "apiKey,imageKitId"
