# Fichier : netlify.toml

[build]
command = "nx build Angular-Movie-App --no-cloud"

publish = "dist/apps/Angular-Movie-App/browser"

[[plugins]]
package = "@netlify/angular-runtime"
  [plugins.inputs]
  packagePath = "."
